"""Change support model to JSON and schema as well

Revision ID: 22e0e7b2eb0b
Revises: 35a7dbcd670e
Create Date: 2026-08-13 14:03:00.755200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22e0e7b2eb0b'
down_revision: Union[str, Sequence[str], None] = '35a7dbcd670e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # Existing NULL company profiles must be converted
    # before applying NOT NULL.
    op.execute("""
        UPDATE proposal_requirements
        SET company_profile = '{}'::json
        WHERE company_profile IS NULL
    """)

    op.alter_column(
        'proposal_requirements',
        'company_profile',
        existing_type=postgresql.JSON(
            astext_type=sa.Text()
        ),
        nullable=False,
    )

    op.alter_column(
        'proposal_requirements',
        'support_model',
        existing_type=sa.TEXT(),
        type_=postgresql.JSON(
            astext_type=sa.Text()
        ),
        postgresql_using="""
            CASE
                WHEN support_model IS NULL THEN NULL
                ELSE json_build_object(
                    'description',
                    support_model
                )
            END
        """,
        existing_nullable=True,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposal_requirements', 'support_model',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('proposal_requirements', 'company_profile',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
