"""Change company profile to JSON

Revision ID: 35a7dbcd670e
Revises: a4505a139cf9
Create Date: 2026-08-13 12:50:10.164288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a7dbcd670e'
down_revision: Union[str, Sequence[str], None] = 'a4505a139cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "proposal_requirements",
        "company_profile",
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        nullable=True,
        postgresql_using="""
            CASE
                WHEN company_profile IS NULL THEN NULL
                ELSE json_build_object(
                    'description',
                    company_profile
                )
            END
        """,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposal_requirements', 'company_profile',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
