"""Make proposal analysis unique per proposal

Revision ID: 3d3a99be864a
Revises: 02bf2cf53610
Create Date: 2026-08-12 11:46:47.266132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3a99be864a'
down_revision: Union[str, Sequence[str], None] = '02bf2cf53610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'proposal_analyses', ['proposal_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposal_analyses', type_='unique')
    # ### end Alembic commands ###
