"""add RFP requirements

Revision ID: 8c4f07c329af
Revises: 7905ac919263
Create Date: 2026-08-08 15:10:13.847860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4f07c329af'
down_revision: Union[str, Sequence[str], None] = '7905ac919263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfp_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfp_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('submission_deadline', sa.String(), nullable=True),
    sa.Column('project_overview', sa.Text(), nullable=True),
    sa.Column('mandatory_requirements', sa.JSON(), nullable=False),
    sa.Column('technical_requirements', sa.JSON(), nullable=False),
    sa.Column('functional_requirements', sa.JSON(), nullable=False),
    sa.Column('deliverables', sa.JSON(), nullable=False),
    sa.Column('evaluation_criteria', sa.JSON(), nullable=False),
    sa.Column('commercial_requirements', sa.JSON(), nullable=False),
    sa.Column('eligibility_requirements', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfp_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfp_requirements')
    # ### end Alembic commands ###
