"""Add pending proposal status

Revision ID: a4505a139cf9
Revises: 3d3a99be864a
Create Date: 2026-08-12 13:48:36.347279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4505a139cf9'
down_revision: Union[str, Sequence[str], None] = '3d3a99be864a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TYPE proposalstatus "
        "ADD VALUE IF NOT EXISTS 'PENDING' "
        "BEFORE 'PROCESSING'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
