"""add proposal requirements

Revision ID: ef78a5394972
Revises: 9e7fb52c86d0
Create Date: 2026-08-10 11:33:04.379708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef78a5394972'
down_revision: Union[str, Sequence[str], None] = '9e7fb52c86d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('company_profile', sa.Text(), nullable=True),
    sa.Column('understanding_of_requirements', sa.Text(), nullable=True),
    sa.Column('proposed_solution', sa.Text(), nullable=True),
    sa.Column('technical_approach', sa.Text(), nullable=True),
    sa.Column('implementation_approach', sa.Text(), nullable=True),
    sa.Column('project_team', sa.JSON(), nullable=False),
    sa.Column('relevant_experience', sa.JSON(), nullable=False),
    sa.Column('deliverables', sa.JSON(), nullable=False),
    sa.Column('support_model', sa.Text(), nullable=True),
    sa.Column('commercial_proposal', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('exceptions', sa.JSON(), nullable=False),
    sa.Column('client_references', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal_requirements')
    # ### end Alembic commands ###
